# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "whiskey_disk"
  s.version = "0.7.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rick Bradley"]
  s.date = "2015-03-24"
  s.description = "Opinionated gem for doing fast git-based server deployments."
  s.email = "rick@rickbradley.com"
  s.executables = ["wd", "wd_role"]
  s.extra_rdoc_files = [
    "README.integration_specs",
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README.integration_specs",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "WHY.txt",
    "bin/wd",
    "bin/wd_role",
    "examples/deploy-configs.yml",
    "examples/deploy-local.yml",
    "examples/deploy-multiple-remotes.yml",
    "examples/deploy-staging.yml",
    "examples/deploy.rake",
    "examples/deploy.yml",
    "init.rb",
    "install.rb",
    "lib/whiskey_disk.rb",
    "lib/whiskey_disk/config.rb",
    "lib/whiskey_disk/helpers.rb",
    "lib/whiskey_disk/rake.rb",
    "spec/.bacon",
    "spec/init_spec.rb",
    "spec/install_spec.rb",
    "spec/spec_helper.rb",
    "spec/wd_command_spec.rb",
    "spec/wd_role_command_spec.rb",
    "spec/whiskey_disk/config_spec.rb",
    "spec/whiskey_disk/helpers_spec.rb",
    "spec/whiskey_disk/rake_spec.rb",
    "spec/whiskey_disk_spec.rb",
    "tasks/deploy.rake",
    "whiskey_disk.gemspec"
  ]
  s.homepage = "http://github.com/flogic/whiskey_disk"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "embarrassingly fast deployments."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<aws-sdk>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<aws-sdk>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<aws-sdk>, [">= 0"])
  end
end

